<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200222205732 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE font (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(15) NOT NULL, real_font_name VARCHAR(15) NOT NULL, active TINYINT(1) NOT NULL, path VARCHAR(127) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE fir_blog CHANGE site_id site_id INT DEFAULT NULL, CHANGE seo_title seo_title VARCHAR(128) DEFAULT NULL, CHANGE seo_description seo_description VARCHAR(256) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_product_code_promotion CHANGE product_id product_id INT DEFAULT NULL, CHANGE date_end date_end DATE DEFAULT NULL, CHANGE stripe_plan_tarifaire_id stripe_plan_tarifaire_id VARCHAR(256) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_contact CHANGE site_id site_id INT DEFAULT NULL, CHANGE presentation presentation VARCHAR(512) DEFAULT NULL, CHANGE email email VARCHAR(512) DEFAULT NULL, CHANGE phone phone VARCHAR(128) DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE post_code post_code VARCHAR(32) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE country country VARCHAR(255) DEFAULT NULL, CHANGE opening_time opening_time VARCHAR(1028) DEFAULT NULL, CHANGE seo_title seo_title VARCHAR(128) DEFAULT NULL, CHANGE seo_description seo_description VARCHAR(256) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_home CHANGE site_id site_id INT DEFAULT NULL, CHANGE mainPicture mainPicture VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE seo_title seo_title VARCHAR(128) DEFAULT NULL, CHANGE seo_description seo_description VARCHAR(256) DEFAULT NULL, CHANGE text_picture text_picture VARCHAR(256) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_invoice CHANGE site_id site_id INT DEFAULT NULL, CHANGE first_name first_name VARCHAR(256) DEFAULT NULL, CHANGE last_name last_name VARCHAR(256) DEFAULT NULL, CHANGE invoice_number invoice_number VARCHAR(256) DEFAULT NULL, CHANGE title title VARCHAR(1024) DEFAULT NULL, CHANGE description description VARCHAR(1024) DEFAULT NULL, CHANGE quantity quantity INT DEFAULT NULL, CHANGE unit_price unit_price DOUBLE PRECISION DEFAULT NULL, CHANGE price price DOUBLE PRECISION DEFAULT NULL, CHANGE vat_rate vat_rate DOUBLE PRECISION DEFAULT NULL, CHANGE total_amount total_amount DOUBLE PRECISION DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT NULL, CHANGE address2 address2 VARCHAR(255) DEFAULT NULL, CHANGE post_code post_code VARCHAR(15) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE country country VARCHAR(63) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_post CHANGE blog_id blog_id INT DEFAULT NULL, CHANGE image image VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_presentation CHANGE site_id site_id INT DEFAULT NULL, CHANGE seo_title seo_title VARCHAR(128) DEFAULT NULL, CHANGE seo_description seo_description VARCHAR(256) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_pricing CHANGE site_id site_id INT DEFAULT NULL, CHANGE seo_title seo_title VARCHAR(128) DEFAULT NULL, CHANGE seo_description seo_description VARCHAR(256) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_pricing_category CHANGE site_id site_id INT DEFAULT NULL, CHANGE description description VARCHAR(1023) DEFAULT NULL, CHANGE display_order display_order INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_pricing_product CHANGE category_id category_id INT DEFAULT NULL, CHANGE site_id site_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_product CHANGE code_promotion code_promotion VARCHAR(15) DEFAULT NULL, CHANGE stripe_plan_tarifaire_id stripe_plan_tarifaire_id VARCHAR(256) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_quote CHANGE site_id site_id INT DEFAULT NULL, CHANGE presentation presentation VARCHAR(512) DEFAULT NULL, CHANGE email email VARCHAR(512) DEFAULT NULL, CHANGE seo_title seo_title VARCHAR(128) DEFAULT NULL, CHANGE seo_description seo_description VARCHAR(256) DEFAULT NULL');
        $this->addSql('DROP INDEX site_domain_idx ON fir_site');
        $this->addSql('DROP INDEX site_internal_name_idx ON fir_site');
        $this->addSql('DROP INDEX site_domain_host_idx ON fir_site');
        $this->addSql('ALTER TABLE fir_site ADD font_id INT NOT NULL, CHANGE code_promotion_id code_promotion_id INT DEFAULT NULL, CHANGE logo logo VARCHAR(255) DEFAULT NULL, CHANGE domain domain VARCHAR(255) DEFAULT NULL, CHANGE key_words key_words VARCHAR(1023) DEFAULT NULL, CHANGE favicon favicon VARCHAR(255) DEFAULT NULL, CHANGE facebook facebook VARCHAR(1023) DEFAULT NULL, CHANGE instagram instagram VARCHAR(1023) DEFAULT NULL, CHANGE twitter twitter VARCHAR(1023) DEFAULT NULL, CHANGE internal_name internal_name VARCHAR(255) DEFAULT NULL, CHANGE stripe_subscription_id stripe_subscription_id VARCHAR(65) DEFAULT NULL, CHANGE command_domain command_domain VARCHAR(255) DEFAULT NULL, CHANGE command_option command_option INT DEFAULT NULL, CHANGE domain_host domain_host VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_site ADD CONSTRAINT FK_D9265D4BD7F7F9EB FOREIGN KEY (font_id) REFERENCES font (id)');
        $this->addSql('CREATE INDEX IDX_D9265D4BD7F7F9EB ON fir_site (font_id)');
        $this->addSql('CREATE INDEX site_internal_name_idx ON fir_site (internal_name)');
        $this->addSql('CREATE INDEX site_domain_host_idx ON fir_site (domain_host)');
        $this->addSql('ALTER TABLE fir_support CHANGE user_id user_id INT DEFAULT NULL, CHANGE type type VARCHAR(256) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_tracking_contact CHANGE site_id site_id INT DEFAULT NULL, CHANGE name name VARCHAR(256) DEFAULT NULL, CHANGE email email VARCHAR(256) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_tracking_quote CHANGE site_id site_id INT DEFAULT NULL, CHANGE name name VARCHAR(256) DEFAULT NULL, CHANGE email email VARCHAR(256) DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_user CHANGE salt salt VARCHAR(255) DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT NULL, CHANGE confirmation_token confirmation_token VARCHAR(180) DEFAULT NULL, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE firstname firstname VARCHAR(63) DEFAULT NULL, CHANGE lastname lastname VARCHAR(63) DEFAULT NULL, CHANGE phone phone VARCHAR(14) DEFAULT NULL, CHANGE stripe_customer_id stripe_customer_id VARCHAR(256) DEFAULT NULL, CHANGE account account VARCHAR(255) DEFAULT NULL, CHANGE address1 address1 VARCHAR(255) DEFAULT NULL, CHANGE address2 address2 VARCHAR(255) DEFAULT NULL, CHANGE postal_code postal_code VARCHAR(15) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE society_name society_name VARCHAR(127) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE fir_user_site CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE audit_associations CHANGE tbl tbl VARCHAR(128) DEFAULT NULL, CHANGE label label VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE audit_logs CHANGE target_id target_id INT DEFAULT NULL, CHANGE blame_id blame_id INT DEFAULT NULL, CHANGE diff diff JSON DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE fir_site DROP FOREIGN KEY FK_D9265D4BD7F7F9EB');
        $this->addSql('DROP TABLE font');
        $this->addSql('ALTER TABLE audit_associations CHANGE tbl tbl VARCHAR(128) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE label label VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE audit_logs CHANGE target_id target_id INT DEFAULT NULL, CHANGE blame_id blame_id INT DEFAULT NULL, CHANGE diff diff TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_blog CHANGE site_id site_id INT DEFAULT NULL, CHANGE seo_title seo_title VARCHAR(128) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE seo_description seo_description VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_contact CHANGE site_id site_id INT DEFAULT NULL, CHANGE presentation presentation VARCHAR(512) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(512) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE phone phone VARCHAR(128) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE name name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE post_code post_code VARCHAR(32) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE city city VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE country country VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE opening_time opening_time VARCHAR(1028) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE seo_title seo_title VARCHAR(128) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE seo_description seo_description VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_home CHANGE site_id site_id INT DEFAULT NULL, CHANGE mainPicture mainPicture VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE text_picture text_picture VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\', CHANGE seo_title seo_title VARCHAR(128) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE seo_description seo_description VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_invoice CHANGE site_id site_id INT DEFAULT NULL, CHANGE first_name first_name VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE last_name last_name VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE invoice_number invoice_number VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE title title VARCHAR(1024) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE description description VARCHAR(1024) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE quantity quantity INT DEFAULT NULL, CHANGE unit_price unit_price DOUBLE PRECISION DEFAULT \'NULL\', CHANGE price price DOUBLE PRECISION DEFAULT \'NULL\', CHANGE vat_rate vat_rate DOUBLE PRECISION DEFAULT \'NULL\', CHANGE total_amount total_amount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE address address VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE address2 address2 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE post_code post_code VARCHAR(15) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE city city VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE country country VARCHAR(63) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_post CHANGE blog_id blog_id INT DEFAULT NULL, CHANGE image image VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_presentation CHANGE site_id site_id INT DEFAULT NULL, CHANGE seo_title seo_title VARCHAR(128) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE seo_description seo_description VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_pricing CHANGE site_id site_id INT DEFAULT NULL, CHANGE seo_title seo_title VARCHAR(128) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE seo_description seo_description VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_pricing_category CHANGE site_id site_id INT DEFAULT NULL, CHANGE description description VARCHAR(1023) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE display_order display_order INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_pricing_product CHANGE site_id site_id INT DEFAULT NULL, CHANGE category_id category_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fir_product CHANGE code_promotion code_promotion VARCHAR(15) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE stripe_plan_tarifaire_id stripe_plan_tarifaire_id VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_product_code_promotion CHANGE product_id product_id INT DEFAULT NULL, CHANGE date_end date_end DATE DEFAULT \'NULL\', CHANGE stripe_plan_tarifaire_id stripe_plan_tarifaire_id VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_quote CHANGE site_id site_id INT DEFAULT NULL, CHANGE presentation presentation VARCHAR(512) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(512) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE seo_title seo_title VARCHAR(128) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE seo_description seo_description VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('DROP INDEX IDX_D9265D4BD7F7F9EB ON fir_site');
        $this->addSql('DROP INDEX site_internal_name_idx ON fir_site');
        $this->addSql('DROP INDEX site_domain_host_idx ON fir_site');
        $this->addSql('ALTER TABLE fir_site DROP font_id, CHANGE code_promotion_id code_promotion_id INT DEFAULT NULL, CHANGE logo logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE domain domain VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE domain_host domain_host VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE key_words key_words VARCHAR(1023) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE favicon favicon VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE facebook facebook VARCHAR(1023) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE instagram instagram VARCHAR(1023) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE twitter twitter VARCHAR(1023) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE internal_name internal_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE stripe_subscription_id stripe_subscription_id VARCHAR(65) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE command_domain command_domain VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE command_option command_option INT DEFAULT NULL');
        $this->addSql('CREATE INDEX site_domain_idx ON fir_site (domain)');
        $this->addSql('CREATE INDEX site_internal_name_idx ON fir_site (internal_name)');
        $this->addSql('CREATE INDEX site_domain_host_idx ON fir_site (domain_host)');
        $this->addSql('ALTER TABLE fir_support CHANGE user_id user_id INT DEFAULT NULL, CHANGE type type VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_tracking_contact CHANGE site_id site_id INT DEFAULT NULL, CHANGE name name VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_tracking_quote CHANGE site_id site_id INT DEFAULT NULL, CHANGE name name VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_user CHANGE salt salt VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE last_login last_login DATETIME DEFAULT \'NULL\', CHANGE confirmation_token confirmation_token VARCHAR(180) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE password_requested_at password_requested_at DATETIME DEFAULT \'NULL\', CHANGE created_at created_at DATETIME DEFAULT \'\'\'2020-01-01 00:00:00\'\'\' NOT NULL, CHANGE firstname firstname VARCHAR(63) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE lastname lastname VARCHAR(63) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE phone phone VARCHAR(14) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE stripe_customer_id stripe_customer_id VARCHAR(256) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE account account VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE address1 address1 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE address2 address2 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE postal_code postal_code VARCHAR(15) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE city city VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE society_name society_name VARCHAR(127) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE fir_user_site CHANGE created_at created_at DATETIME DEFAULT \'NULL\'');
    }
}
